3. El archivo .txt no se encuentra en el repositorio remoto porque aún no realicé el push correspondiente.

5. El cambio realizado desde el repositorio remoto no se ve localmente porque aún no realicé el pull correspondiente.

8. Desde el lugar donde realicé el primer push no sucedió nada, pero el segundo me dio un error. Esto sucedió porque estaba trabajando con un archivo desactualizado después del primer push, así que para proseguir realicé un merge para unir los distintos cambios.